// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: logging/yarder/yarder.proto

package yarder_connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	yarder "github.com/kellegous/glue/logging/yarder"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// YarderName is the fully-qualified name of the Yarder service.
	YarderName = "yarder.Yarder"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// YarderLogProcedure is the fully-qualified name of the Yarder's Log RPC.
	YarderLogProcedure = "/yarder.Yarder/Log"
)

// YarderClient is a client for the yarder.Yarder service.
type YarderClient interface {
	Log(context.Context, *connect.Request[yarder.LogReq]) (*connect.Response[emptypb.Empty], error)
}

// NewYarderClient constructs a client for the yarder.Yarder service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewYarderClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) YarderClient {
	baseURL = strings.TrimRight(baseURL, "/")
	yarderMethods := yarder.File_logging_yarder_yarder_proto.Services().ByName("Yarder").Methods()
	return &yarderClient{
		log: connect.NewClient[yarder.LogReq, emptypb.Empty](
			httpClient,
			baseURL+YarderLogProcedure,
			connect.WithSchema(yarderMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
	}
}

// yarderClient implements YarderClient.
type yarderClient struct {
	log *connect.Client[yarder.LogReq, emptypb.Empty]
}

// Log calls yarder.Yarder.Log.
func (c *yarderClient) Log(ctx context.Context, req *connect.Request[yarder.LogReq]) (*connect.Response[emptypb.Empty], error) {
	return c.log.CallUnary(ctx, req)
}

// YarderHandler is an implementation of the yarder.Yarder service.
type YarderHandler interface {
	Log(context.Context, *connect.Request[yarder.LogReq]) (*connect.Response[emptypb.Empty], error)
}

// NewYarderHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewYarderHandler(svc YarderHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	yarderMethods := yarder.File_logging_yarder_yarder_proto.Services().ByName("Yarder").Methods()
	yarderLogHandler := connect.NewUnaryHandler(
		YarderLogProcedure,
		svc.Log,
		connect.WithSchema(yarderMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	return "/yarder.Yarder/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case YarderLogProcedure:
			yarderLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedYarderHandler returns CodeUnimplemented from all methods.
type UnimplementedYarderHandler struct{}

func (UnimplementedYarderHandler) Log(context.Context, *connect.Request[yarder.LogReq]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("yarder.Yarder.Log is not implemented"))
}
