// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: logging/yarder/yarder.proto

package yarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	WriterKey     []byte                 `protobuf:"bytes,2,opt,name=writer_key,json=writerKey,proto3" json:"writer_key,omitempty"`
	WriterSeq     uint64                 `protobuf:"varint,3,opt,name=writer_seq,json=writerSeq,proto3" json:"writer_seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogReq) Reset() {
	*x = LogReq{}
	mi := &file_logging_yarder_yarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReq) ProtoMessage() {}

func (x *LogReq) ProtoReflect() protoreflect.Message {
	mi := &file_logging_yarder_yarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReq.ProtoReflect.Descriptor instead.
func (*LogReq) Descriptor() ([]byte, []int) {
	return file_logging_yarder_yarder_proto_rawDescGZIP(), []int{0}
}

func (x *LogReq) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *LogReq) GetWriterKey() []byte {
	if x != nil {
		return x.WriterKey
	}
	return nil
}

func (x *LogReq) GetWriterSeq() uint64 {
	if x != nil {
		return x.WriterSeq
	}
	return 0
}

func (x *LogReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_logging_yarder_yarder_proto protoreflect.FileDescriptor

const file_logging_yarder_yarder_proto_rawDesc = "" +
	"\n" +
	"\x1blogging/yarder/yarder.proto\x12\x06yarder\x1a\x1bgoogle/protobuf/empty.proto\"l\n" +
	"\x06LogReq\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x1d\n" +
	"\n" +
	"writer_key\x18\x02 \x01(\fR\twriterKey\x12\x1d\n" +
	"\n" +
	"writer_seq\x18\x03 \x01(\x04R\twriterSeq\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data27\n" +
	"\x06Yarder\x12-\n" +
	"\x03Log\x12\x0e.yarder.LogReq\x1a\x16.google.protobuf.EmptyB*Z(github.com/kellegous/glue/logging/yarderb\x06proto3"

var (
	file_logging_yarder_yarder_proto_rawDescOnce sync.Once
	file_logging_yarder_yarder_proto_rawDescData []byte
)

func file_logging_yarder_yarder_proto_rawDescGZIP() []byte {
	file_logging_yarder_yarder_proto_rawDescOnce.Do(func() {
		file_logging_yarder_yarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logging_yarder_yarder_proto_rawDesc), len(file_logging_yarder_yarder_proto_rawDesc)))
	})
	return file_logging_yarder_yarder_proto_rawDescData
}

var file_logging_yarder_yarder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logging_yarder_yarder_proto_goTypes = []any{
	(*LogReq)(nil),        // 0: yarder.LogReq
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_logging_yarder_yarder_proto_depIdxs = []int32{
	0, // 0: yarder.Yarder.Log:input_type -> yarder.LogReq
	1, // 1: yarder.Yarder.Log:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logging_yarder_yarder_proto_init() }
func file_logging_yarder_yarder_proto_init() {
	if File_logging_yarder_yarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logging_yarder_yarder_proto_rawDesc), len(file_logging_yarder_yarder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logging_yarder_yarder_proto_goTypes,
		DependencyIndexes: file_logging_yarder_yarder_proto_depIdxs,
		MessageInfos:      file_logging_yarder_yarder_proto_msgTypes,
	}.Build()
	File_logging_yarder_yarder_proto = out.File
	file_logging_yarder_yarder_proto_goTypes = nil
	file_logging_yarder_yarder_proto_depIdxs = nil
}
